// <auto-generated />
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DataAccess.Migrations
{
    [DbContext(typeof(BancoDeDados))]
    [Migration("20180203211334_AdicioandoBaseComputador")]
    partial class AdicioandoBaseComputador
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataAccess.Domain.Computador", b =>
                {
                    b.Property<int>("IdCompuatador")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Disponivel");

                    b.Property<string>("PlacaDeVideo");

                    b.Property<string>("Processador")
                        .IsRequired();

                    b.Property<int>("QtdEspacoHd");

                    b.Property<int>("QtdMemoriaRam");

                    b.HasKey("IdCompuatador");

                    b.ToTable("Computadores");
                });
#pragma warning restore 612, 618
        }
    }
}
